# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0016_auto_20160411_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disquscomment',
            name='md_file',
        ),
        migrations.RemoveField(
            model_name='duoshuocomment',
            name='md_file',
        ),
        migrations.DeleteModel(
            name='DisqusComment',
        ),
        migrations.DeleteModel(
            name='DuoshuoComment',
        ),
    ]
