# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0017_auto_20160723_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('wb_url', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True,
                                               verbose_name=b'WeiboURL')),
                ('wb_text', models.TextField(default=b'Default text.', verbose_name=b'WeiboText')),
                ('wb_pub_time', models.DateTimeField(null=True, verbose_name=b'Publish Time')),
                ('wb_mod_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'Modify Time')),
                ('wb_visit', models.IntegerField(null=True, verbose_name=b'Visits')),
                ('wb_draft', models.NullBooleanField(default=False)),
            ],
            options={
                'ordering': ['-wb_pub_time'],
                'get_latest_by': '-wb_pub_time',
                'verbose_name': '\u5fae\u535a',
                'verbose_name_plural': '\u5fae\u535a',
            },
        ),
    ]
