# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0018_weibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_tag_name', models.CharField(max_length=32, unique=True, verbose_name=b'WeiboTagName')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
    ]
