# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0019_weibotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='wb_url',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
