# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0021_auto_20160723_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='wb_visit',
            field=models.IntegerField(default=0, null=True, verbose_name=b'Visits'),
        ),
    ]
