# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0022_auto_20160723_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='wb_tag',
            field=models.ManyToManyField(default=b'untagged', null=True, to='blog.WeiboTag', verbose_name=b'Tag'),
        ),
    ]
