# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0023_weibo_wb_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibotag',
            options={'verbose_name': '\u5fae\u535a\u6807\u7b7e', 'verbose_name_plural': '\u5fae\u535a\u6807\u7b7e'},
        ),
    ]
