# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0026_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image_file',
            field=models.ImageField(upload_to=b'img', verbose_name=b'ImageFile'),
        ),
    ]
