# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_mdfile_md_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_full_path', models.URLField(verbose_name=b'BackgroundURL')),
                ('url_name', models.CharField(max_length=128, verbose_name=b'URLName')),
                ('url_is_published', models.NullBooleanField(default=False, verbose_name=b'Published')),
            ],
            options={
                'verbose_name': '\u80cc\u666f\u56fe\u7247',
                'verbose_name_plural': '\u80cc\u666f\u56fe\u7247',
            },
        ),
        migrations.AlterField(
            model_name='weibo',
            name='wb_pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name=b'Publish Time'),
        ),
    ]
