# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20171219_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_visit', models.IntegerField(default=0, verbose_name=b'Site Visits')),
                ('time_visit', models.DateTimeField(verbose_name=b'Visit Time')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u8bbf\u95ee\u7edf\u8ba1\uff08\u6bcf\u5c0f\u65f6\uff09',
                'verbose_name_plural': '\u7f51\u7ad9\u8bbf\u95ee\u7edf\u8ba1\uff08\u6bcf\u5c0f\u65f6\uff09',
            },
        ),
    ]
