# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20171219_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'verbose_name': '\u7f51\u7ad9\u8bbf\u95ee\u7edf\u8ba1', 'verbose_name_plural': '\u7f51\u7ad9\u8bbf\u95ee\u7edf\u8ba1'},
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='month_visit',
            field=models.CharField(default=b'2017-12', max_length=32, verbose_name=b'Visit Month'),
            preserve_default=False,
        ),
    ]
